"""empty message

Revision ID: 8c0e41ac420e
Revises: b54309d9b648
Create Date: 2022-04-09 12:47:17.280333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0e41ac420e'
down_revision = 'b54309d9b648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.add_column('user', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('user', 'isbn_number')
    op.drop_column('user', 'author_name')
    op.drop_column('user', 'title')
    op.drop_column('user', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('author_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('isbn_number', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
